server:
  port: 39080
  servlet-path: /
  session:
    timeout: 30
spring:
  aop:
    auto: true
    proxy-target-class: true
  messages:
    always-use-message-format: true
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true
#mybatis
mybatis:
  type-aliases-package: com.utsoft.blockchain.core.dao.model
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
#mappers multiple interface
mapper:
  mappers: com.utsoft.blockchain.core.dao.MySqlBaseMapper
  not-empty: false
  identity: MYSQL

#############fabric-sdk##########################################
fabric:
  gossipWaitTime: 10000
  invokeWaitTime: 100000
  deployWaitTime: 120000
  proposalWaitTime: 120000
  peer_root_path: channel/crypto-config/peerOrganizations/
  order_root_path: channel/crypto-config/ordererOrganizations/
#############motan-config###############
motan:
  config:
    group: blockchainTransaction
    application: blockchanin